version = 1
[custom]
enable_rule_generator = true
overwrite_original_rules = true
clash_rule_base = "https://raw.githubusercontent.com/ikali/ACL4SSR/main/Clash/base/ownuseClashConfig.yml"

[[custom_groups]]
name = "â„ï¸ èŠ‚ç‚¹é€‰æ‹©"
type = "select"
rule = [
    "[]ğŸ‡¯ğŸ‡µ å¤œæ¡œç§˜æ¹¯",
    "[]ğŸ‡­ğŸ‡° èœ¡ç¬”ç‹å›½",
    "[]ğŸ‡¹ğŸ‡¼ è“¬èŠç‰æ",
    "[]ğŸ‡¸ğŸ‡¬ æ˜Ÿç©ºæµ´å ´",
    "[]ğŸ‡ºğŸ‡¸ é™½å…‰æµ·å²¸",
    "[]â™¨ï¸ æ‰‹åŠ¨é€‰æ‹©",
    "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©",
    "[]ğŸ”¯ æ•…éšœè½¬ç§»",
    "[]ğŸ”® è´Ÿè½½å‡è¡¡",
    "[]ğŸ® å†·é—¨è´Ÿè½½"
]

[[custom_groups]]
name = "â™¨ï¸ æ‰‹åŠ¨é€‰æ‹©"
type = "select"
rule = [".*"]

[[custom_groups]]
name = "ğŸ æ¼ç½‘ä¹‹é±¼"
type = "select"
rule = [
    ".*",
    "[]DIRECT"
]

[[custom_groups]]
name = "ğŸ‡¯ğŸ‡µ å¤œæ¡œç§˜æ¹¯"
type = "select"
rule = [
    "(ğŸ‡¯ğŸ‡µ|JP|Japan|æ—¥æœ¬|ä¸œäº¬|å¤§é˜ª|åŸ¼ç‰|[^-]æ—¥)",
    "[]REJECT"
]

[[custom_groups]]
name = "ğŸ‡­ğŸ‡° èœ¡ç¬”ç‹å›½"
type = "select"
rule = [
    "(ğŸ‡­ğŸ‡°|HK|Hong Kong|HongKong|[^-]æ¸¯)",
    "[]REJECT"
]

[[custom_groups]]
name = "ğŸ‡¹ğŸ‡¼ è“¬èŠç‰æ"
type = "select"
rule = [
    "(ğŸ‡¹ğŸ‡¼|TW|Taiwan|[^-]å°|æ–°åŒ—|å½°åŒ–|HINET)",
    "[]REJECT"
]

[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ æ˜Ÿç©ºæµ´å ´"
type = "select"
rule = [
    "(ğŸ‡¸ğŸ‡¬|SG|Singapore|æ–°åŠ å¡|ç‹®åŸ|[^-]æ–°)",
    "[]REJECT"
]

[[custom_groups]]
name = "ğŸ‡ºğŸ‡¸ é™½å…‰æµ·å²¸"
type = "select"
rule = [
    "(ğŸ‡ºğŸ‡¸|US|United States|[^-]ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥)",
    "[]REJECT"
]

[[custom_groups]]
name = "ğŸ¯ å…¨çƒç›´è¿"
type = "select"
rule = [
    "[]DIRECT",
    "[]â™¨ï¸ æ‰‹åŠ¨é€‰æ‹©"
]

[[custom_groups]]
name = "â™»ï¸ è‡ªåŠ¨é€‰æ‹©"
type = "url-test"
lazy = true
rule = [
    "[]ğŸ‡¯ğŸ‡µ å¤œæ¡œç§˜æ¹¯",
    "[]ğŸ‡­ğŸ‡° èœ¡ç¬”ç‹å›½",
    "[]ğŸ‡¹ğŸ‡¼ è“¬èŠç‰æ",
    "[]ğŸ‡¸ğŸ‡¬ æ˜Ÿç©ºæµ´å ´",
    "[]ğŸ‡ºğŸ‡¸ é™½å…‰æµ·å²¸"
]
url = "http://www.apple.com/library/test/success.html"
interval = 300
tolerance = 100

[[custom_groups]]
name = "ğŸ”¯ æ•…éšœè½¬ç§»"
type = "fallback"
lazy = true
rule = [
    "[]ğŸ‡¯ğŸ‡µ å¤œæ¡œç§˜æ¹¯",
    "[]ğŸ‡­ğŸ‡° èœ¡ç¬”ç‹å›½",
    "[]ğŸ‡¹ğŸ‡¼ è“¬èŠç‰æ",
    "[]ğŸ‡¸ğŸ‡¬ æ˜Ÿç©ºæµ´å ´",
    "[]ğŸ‡ºğŸ‡¸ é™½å…‰æµ·å²¸"
]
url = "http://www.apple.com/library/test/success.html"
interval = 300

[[custom_groups]]
name = "ğŸ”® è´Ÿè½½å‡è¡¡"
type = "load-balance"
strategy = "round-robin"
lazy = true
rule = [
    "[]ğŸ‡¯ğŸ‡µ å¤œæ¡œç§˜æ¹¯",
    "[]ğŸ‡­ğŸ‡° èœ¡ç¬”ç‹å›½",
    "[]ğŸ‡¹ğŸ‡¼ è“¬èŠç‰æ",
    "[]ğŸ‡¸ğŸ‡¬ æ˜Ÿç©ºæµ´å ´",
    "[]ğŸ‡ºğŸ‡¸ é™½å…‰æµ·å²¸"
]
url = "http://www.apple.com/library/test/success.html"
interval = 300

[[custom_groups]]
name = "ğŸ® å†·é—¨è´Ÿè½½"
type = "load-balance"
strategy = "round-robin"
lazy = true
rule = [".*^(?!.*(ğŸ‡¯ğŸ‡µ|ğŸ‡­ğŸ‡°|ğŸ‡¹ğŸ‡¼|ğŸ‡¸ğŸ‡¬|ğŸ‡ºğŸ‡¸|ğŸ‡¨ğŸ‡³|IPLC))"]
url = "http://www.apple.com/library/test/success.html"
interval = 300

[[rulesets]]
group = "â„ï¸ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "https://raw.githubusercontent.com/ikali/ACL4SSR/main/Clash/rules/Direct.list"

[[rulesets]]
group = "DIRECT"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "ğŸ æ¼ç½‘ä¹‹é±¼"
ruleset = "[]FINAL"

[emojis]
add_emoji = true
remove_old_emoji = true

[[emojis.emoji]]
import = "https://raw.githubusercontent.com/ikali/ACL4SSR/main/Clash/base/emoji.toml"

clash_proxies_style = "flow"
